triggers:
  - name: on-sync-unknown
    condition: app.status.sync.status == 'Unknown'
    template: app-sync-status

templates:
  - name: app-sync-status
    title: Application {{.app.metadata.name}} sync status is {{.app.status.sync.status}}
    body: |
      Application {{.app.metadata.name}} sync is {{.app.status.sync.status}}.
      Application details: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}.

context:
  argocdUrl: https://argocd.myhost.com