apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- argocd-notifications-controller-rolebinding.yaml
- argocd-notifications-controller-sa.yaml
- argocd-notifications-cm.yaml
- argocd-notifications-controller-deployment.yaml
- argocd-notifications-secret.yaml
- argocd-notifications-controller-role.yaml

images:
  - name: argoprojlabs/argocd-notifications
    newTag: v0.6.0
