apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-notifications-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-notifications-controller
rules:
- apiGroups:
  - argoproj.io
  resources:
  - applications
  - appprojects
  verbs:
  - list
  - watch
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-notifications-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-notifications-controller
subjects:
- kind: ServiceAccount
  name: argocd-notifications-controller
---
apiVersion: v1
data:
  config.yaml: '{}'
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
stringData:
  notifiers.yaml: |
    email:
      host: smtp.gmail.com
      port: 587
      from: <myemail>@gmail.com
      username: <myemail>@gmail.com
      password: <mypassword>
    slack:
      token: <my-token>
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-notifications-controller
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-notifications-controller
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-notifications-controller
    spec:
      containers:
      - command:
        - /app/argocd-notifications-controller
        - --config
        - /app/config/config.yaml
        - --notifiers
        - /app/secret/notifiers.yaml
        image: alexmt/argocd-notifications:latest
        imagePullPolicy: Always
        name: argocd-notifications-controller
        volumeMounts:
        - mountPath: /app/config
          name: config
        - mountPath: /app/secret
          name: notifiers
        workingDir: /app
      serviceAccountName: argocd-notifications-controller
      volumes:
      - name: notifiers
        secret:
          secretName: argocd-notifications-secret
      - configMap:
          name: argocd-notifications-cm
        name: config
